version: 2
jobs:
  build:
    working_directory: ~/spinnup
    docker:
      - image: fluuuid/circleci:latest
    branches:
      only:
        - master
        - develop
        - /feature.*/
    steps:
      - checkout
      - run:
          name: "Check Dependencies version"
          command: |
            node --version
            yarn --version
            aws --version
      - run:
          name: "Install dependencies"
          command: yarn
      - run:
          name: "Run tests"
          command: yarn test
      - run:
          name: Setup AWS credentials
          command: |
            mkdir ~/.aws && printf "[profile eb-cli]\naws_access_key_id = ${AWS_ACCESS_KEY_ID}\naws_secret_access_key = ${AWS_SECRET_ACCESS_KEY}" > ~/.aws/config
      - deploy:
          name: "Deploy to S3"
          command: |
            if [ "${CIRCLE_BRANCH}" == "develop" ]; then
              export PATH="./node_modules/.bin/:$PATH"
              yarn build
              aws s3 sync dist s3://fluuu.id/projects/spinnup --exclude \"*.git/*\" --exclude \"*/node_modules/*\" --exclude \"npm-debug.log\" --exclude \"*/jspm_packages/*\" --delete
              aws cloudfront create-invalidation --distribution-id E1VQPKJ3HV2UQ2 --paths /projects/spinnup/viz.html /projects/spinnup/index.html
            fi
